version: "3"
services:
  api:
    ports:
      - "8000:80"
    links:
      - db
    build: .
    networks:
      - deltax
    restart: always
  db:
    image: mongo
    restart: always
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"
    networks:
      - deltax

networks:
  deltax:
    driver: bridge

volumes:
    dbdata:
